# Generated by Django 3.2.5 on 2021-08-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=1000)),
                ('bio', models.TextField()),
                ('age', models.IntegerField()),
                ('data_created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
