# Generated by Django 3.2.5 on 2021-09-21 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='ListUser',
        ),
    ]
