# Generated by Django 3.2.5 on 2021-09-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0003_alter_listuser_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('address', models.CharField(max_length=1000)),
                ('bio', models.TextField()),
                ('age', models.IntegerField()),
                ('data_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ListUser',
        ),
    ]
