# Generated by Django 3.2.5 on 2021-10-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0005_auto_20211002_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listdetail',
            name='contactNumber',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
